daemon:
  image: guacamole/guacd:1.5.4
  replicas: 1
  nodeSelector: {}
  tolerations: []
  volumes: []
  volumeMounts: []
  env: []
  resources: {}
  port: "4822"
  service:
    port: "4822"

portal:
  image: guacamole/guacamole:1.5.4
  replicas: 1
  nodeSelector: {}
  tolerations: []
  volumes: []
  volumeMounts: []
  env: []
  resources: {}
  port: "8080"
  service:
    port: "8080"
  ingress:
    enabled: true
    annotations: {}
    className: nginx
    host: guacamole.lsc-sde.local
    tls:
      enabled: false
      secretName: "guacamole-tls"

client:
  enabled: true
  image: lscsde/analytics-vnc-client:0.1.3
  replicas: 1
  nodeSelector: {}
  tolerations: []
  volumes: []
  volumeMounts: []
  env: []
  resources: {}
  port: "5900"
  service:
    port: "5900"

database:
  type: postgres
  hostname: "cluster.lsc-sde.local"
  port: "5432"
  database: "guacamole"
  user: "guac@cluster.lsc-sde.local"
  password:
    secret: "guacamole"
    key: "db-password"