apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ include "guacamole.portal.name" . }}
  name: portal
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: {{ include "guacamole.portal.name" . }}
  ports:
  - name: http
    port: {{ .Values.portal.service.port }}
    protocol: TCP
    targetPort: {{ .Values.portal.port }}