apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ include "guacamole.client.name" . }}
  name: client
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: {{ include "guacamole.client.name" . }}
  ports:
  - name: http
    port: {{ .Values.client.service.port }}
    protocol: TCP
    targetPort: {{ .Values.client.port }}