apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ include "guacamole.daemon.name" . }}
  name: daemon
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: {{ include "guacamole.daemon.name" . }}
  ports:
  - name: daemon
    port: {{ .Values.daemon.service.port }}
    protocol: TCP
    targetPort: {{ .Values.daemon.port }}