name: Deploy new Helm Package

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'

jobs:
  release:
    uses: lsc-sde/lsc-sde/.github/workflows/helm-release.yaml@main
    with:
      directory: products/sde-3rd-party/guacamole/iac-helm-guacamole
      yamlPath: guacamole
    secrets: inherit
